#
# Makefile for dummy poly_acc library
#

# What to install, and where to install it
INSTALL_TARGS = poly_acc.lib pa_enabl.h poly_acc.h

# What libs to build
LIBS = poly_acc

# What objs in the poly_acc lib
POLY_ACC_OBJS = poly_acc.obj

# What to clean
CLEAN_TARGS = $(OBJDIR)\*.obj

#rules and targets common to all Miner makefiles
%include $(INIT)\makefile.def

### OPUS MKMF:  Do not remove this line!  Generated dependencies follow.


