#
# $Source: f:/miner/source/novga/rcs/makefile $
# $Revision: 1.2 $
# $Author: samir $
# $Date: 1996/03/15 19:05:21 $
#
# Makefile for nonvga functions
#

# What to install, and where to install it
INSTALL_TARGS = novga.lib

# What to clean
CLEAN_TARGS = $(OBJDIR)\*.obj

# What libs to make
LIBS = novga


# What object files for the lib
NOVGA_OBJS = novesa.obj 

#rules and targets common to all Miner makefiles
%include $(INIT)\makefile.def

### OPUS MKMF:  Do not remove this line!  Generated dependencies follow.

novesa.obj: fix.h gr.h pstypes.h
