del new\TMAPFLAT.C
del new\SCANLINE.C
del new\TMAP_FLT.ASM
del new\TEXMAPL.H
del new\TMAPFADE.ASM
del new\TEXMAP.H
del new\SCANLINE.H
del new\TMAP_LNT.ASM
del new\TMAP_LLT.ASM
del new\TMAP_INC.ASM
del new\TMAP_PER.ASM
del new\TMAP_ED.ASM
del new\TMAP_LLN.ASM
del new\TMAP_LNN.ASM
del new\TMAP_PLT.ASM
del new\NTMAPOUT.H
del new\TMAP_PNT.ASM
del new\TMAP_PNN.ASM
del new\TMAP_QLT.ASM
del new\TMAP_PLN.ASM
del new\TMAP_QNN.ASM
del new\TMAP_QNT.ASM
del new\TMAP_QLN.ASM
del new\MAKEFILE
