#
# Master makefile for Miner source
#
# Makes all the executable by visiting subdirs and making there
#

CLEAN_TARGS = $(OBJDIR)\*.obj

INSTALL_TARGS = cfile.lib cfile.h nocfile.h

LIBS = cfile

CFILE_OBJS = cfile.obj

#all Miner makefiles should include this
%include $(INIT)\makefile.def
### OPUS MKMF:  Do not remove this line!  Generated dependencies follow.

cfile.obj: cfile.h conio.h ctype.h dos.h errno.h error.h fcntl.h i86.h io.h \
	 mem.h stat.h stdarg.h stdio.h stdlib.h string.h time.h types.h

test.obj: cfile.h cflib.h io.h stat.h stdio.h stdlib.h string.h types.h
